# Generated by Django 3.2.9 on 2021-12-04 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
