# Generated by Django 3.2.9 on 2021-12-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20211204_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
