# Generated by Django 3.2.9 on 2021-12-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_input_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='description',
            field=models.CharField(default='add', max_length=100),
        ),
        migrations.AlterField(
            model_name='input',
            name='task',
            field=models.CharField(default='add', max_length=100),
        ),
    ]
