# Generated by Django 3.2.9 on 2021-12-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20211205_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='input',
            name='task',
            field=models.CharField(default='', max_length=100),
        ),
    ]
