# Generated by Django 3.2.9 on 2021-12-10 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20211210_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='compulsory',
        ),
        migrations.RemoveField(
            model_name='input',
            name='description',
        ),
        migrations.RemoveField(
            model_name='input',
            name='time',
        ),
    ]
