# Generated by Django 3.2.9 on 2021-12-10 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20211210_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='compulsory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='input',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='input',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
